import React from 'react';

const About = () => {
    return (
        <div >
            <h1 className="text-center">ABOUT US</h1> <hr/>
            <p className="m-5">Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis deserunt nobis possimus in quis, praesentium aspernatur aut laborum fuga ratione dolore ea dolores tempora doloribus eligendi, asperiores dicta nemo qui adipisci amet saepe beatae architecto! Nesciunt eaque distinctio nemo ipsam ratione, ad explicabo culpa molestiae totam iusto aspernatur fuga corrupti. Deserunt ducimus asperiores quam, excepturi voluptatibus delectus voluptate, officia neque minus ipsum, repellat molestiae iusto placeat eaque! Saepe consequatur illo dignissimos voluptate obcaecati facilis. Ipsam eos nisi labore atque ullam voluptas sapiente aperiam maiores rem eius doloremque quia praesentium nesciunt quae architecto ipsum sunt eveniet, earum voluptatibus quibusdam perferendis voluptates! At, beatae quia iusto, distinctio earum dolore architecto, corrupti a culpa porro pariatur accusantium ipsam perferendis inventore illo necessitatibus officiis eius quas. Minima mollitia blanditiis voluptatum tenetur natus eos totam? Ex voluptates delectus eveniet vel itaque laudantium nihil, odit voluptatum nam debitis rerum soluta doloremque. Ad magni vel laborum aliquam saepe non voluptatem nemo! Consequuntur exercitationem repellendus natus, odio, maxime repudiandae, recusandae itaque voluptas dicta explicabo nobis accusantium? A, voluptates? Corporis nesciunt magnam perferendis explicabo provident sequi a debitis perspiciatis! Quo quas earum dolorem quia omnis porro repellat.si labore atque ullam voluptas sapiente aperiam maiores rem eius doloremque quia praesentium nesciunt quae architecto ipsum sunt eveniet, earum voluptatibus quibusdam perferendis voluptates! At, beatae quia iusto, distinctio earum dolore architecto, corrupti a culpa porro pariatur accusantium ipsam perferendis inventore illo necessitatibus officiis eius quas. Minima mollitia blanditiis voluptatum tenetur natus eos totam? Ex voluptates delectus eveniet vel itaque laudantium nihil, odit voluptatum nam debitis rerum soluta doloremque. Ad magni vel laborum aliquam saepe non voluptatem nemo! Consequuntur exercitationem repellendus natus, odio, maxime repudiandae, recusandae itaque voluptas dicta explicabo nobis accusantium? A, voluptates? Corporis nesciunt magnam perferendis explicabo provident sequi a debitis perspiciatis! Quo quas earum dolorem quia omnis porro rep Recusandae ipsam error reprehenderit? Similique illum blanditiis voluptates vitae aliquid suscipit veritatis.</p>
        </div>
    );
};

export default About;