export const apartmentData = [
    {
        id: '101',
        name: 'Single Economy',
        photo: 'https://i.ibb.co/KFMXt5f/single-1.jpg',
        location: 'Dhaka',
        RoomType: 'Single',
        bed: 1,
        bath: 1,
        price: 3000,
        flatSize: 1500,
        address: 'Dhanmandi 27 Dhaka',
        TV: 'No',
        Wifi: 'Yes',
        Breakfast: 'Yes',
        SwimmingPool: 'No',
        Parking: 'No'

    },
    {
        id: '102',
        name: 'Single Standard',
        photo: 'https://i.ibb.co/KFMXt5f/single-1.jpg',
        location: 'Dhaka',
        RoomType: 'Single',
        bed: 1,
        bath: 1,
        price: 4000,
        flatSize: 1800,
        address: 'Mirpur 10 Dhaka',
        TV: 'Yes',
        Wifi: 'Yes',
        Breakfast: 'Yes',
        SwimmingPool: 'No',
        Parking: 'No'
    },
    {
        id: '103',
        name: 'Single Delux',
        photo: 'https://i.ibb.co/KFMXt5f/single-1.jpg',
        location: 'Sylhet',
        RoomType: 'Single',
        bed: 1,
        bath: 1,
        price: 5000,
        flatSize: 2000,
        address: 'Zindabazar 22 Sylhet',
        TV: 'Yes',
        Wifi: 'Yes',
        Breakfast: 'Yes',
        SwimmingPool: 'Yes',
        Parking: 'No'
    },
    {
        id: '104',
        name: 'Single Delux two',
        photo: 'https://i.ibb.co/KFMXt5f/single-1.jpg',
        location: 'Chattagram',
        RoomType: 'Single',
        bed: 1,
        bath: 1,
        price: 5500,
        flatSize: 2000,
        address: 'GEC More 15 Chattagram',
        TV: 'Yes',
        Wifi: 'Yes',
        Breakfast: 'Yes',
        SwimmingPool: 'Yes',
        Parking: 'Yes'
    },
    {
        id: '105',
        name: 'Double Economy',
        photo: 'https://i.ibb.co/6nx0HTH/double-1.jpg',
        location: 'Dhaka',
        RoomType: 'Double',
        bed: 1,
        bath: 1,
        price: 5000,
        flatSize: 2000,
        address: 'Dhanmandi 15 Dhaka',
        TV: 'No',
        Wifi: 'Yes',
        Breakfast: 'Yes',
        SwimmingPool: 'No',
        Parking: 'No'
    },
    {
        id: '106',
        name: 'Double standard',
        photo: 'https://i.ibb.co/6nx0HTH/double-1.jpg',
        location: 'Dhaka',
        RoomType: 'Double',
        bed: 2,
        bath: 1,
        price: 6000,
        flatSize: 2000,
        address: 'Mirpur 14 Dhaka',
        TV: 'Yes',
        Wifi: 'Yes',
        Breakfast: 'Yes',
        SwimmingPool: 'No',
        Parking: 'No'
    },
    {
        id: '107',
        name: 'Double delux',
        photo: 'https://i.ibb.co/6nx0HTH/double-1.jpg',
        location: 'Sylhet',
        RoomType: 'Double',
        bed: 2,
        bath: 2,
        price: 6500,
        flatSize: 2200,
        address: 'Noyasarak 13 Sylhet',
        TV: 'Yes',
        Wifi: 'Yes',
        Breakfast: 'Yes',
        SwimmingPool: 'Yes',
        Parking: 'No'
    },
    {
        id: '108',
        name: 'Double Delux two',
        photo: 'https://i.ibb.co/6nx0HTH/double-1.jpg',
        location: 'Chattagram',
        RoomType: 'Double',
        bed: 2,
        bath: 2,
        price: 6700,
        flatSize: 2200,
        address: 'Noyasarak 12 Chattagram',
        TV: 'Yes',
        Wifi: 'Yes',
        Breakfast: 'Yes',
        SwimmingPool: 'Yes',
        Parking: 'Yes'
    },
    {
        id: '109',
        name: 'Family Economy',
        photo: 'https://i.ibb.co/b7Z5tcw/Family-1.jpg',
        location: 'Dhaka',
        RoomType: 'Family',
        bed: 3,
        bath: 2,
        price: 8500,
        flatSize: 4000,
        address: 'Dhanmandi 27 Dhaka',
        TV: 'Yes',
        Wifi: 'Yes',
        Breakfast: 'No',
        SwimmingPool: 'No',
        Parking: 'No'
    },
    {
        id: '110',
        name: 'Family Standard',
        photo: 'https://i.ibb.co/b7Z5tcw/Family-1.jpg',
        location: 'Dhaka',
        RoomType: 'Family',
        bed: 3,
        bath: 2,
        price: 8800,
        flatSize: 4400,
        address: 'Dhanmandi 27 Dhaka',
        TV: 'Yes',
        Wifi: 'Yes',
        Breakfast: 'Yes',
        SwimmingPool: 'No',
        Parking: 'No'

    },
    {
        id: '111',
        name: 'Family Delux',
        photo: 'https://i.ibb.co/b7Z5tcw/Family-1.jpg',
        location: 'Sylhet',
        RoomType: 'Family',
        bed: 3,
        bath: 3,
        price: 9500,
        flatSize: 4600,
        address: 'Zindabazar 2 Sylhet',
        TV: 'Yes',
        Wifi: 'Yes',
        Breakfast: 'Yes',
        SwimmingPool: 'Yes',
        Parking: 'No'
    },
    {
        id: '112',
        name: 'Family Delux two',
        photo: 'https://i.ibb.co/b7Z5tcw/Family-1.jpg',
        location: 'Chattagram',
        RoomType: 'Family',
        bed: 3,
        bath: 3,
        price: 10000,
        flatSize: 5000,
        address: '2nd gate Chattagram',
        TV: 'Yes',
        Wifi: 'Yes',
        Breakfast: 'Yes',
        SwimmingPool: 'Yes',
        Parking: 'Yes'

    }
];
